var aboutTitle = "About Us";
var aboutBody = "TMS is the governing and consultative marketing arm of the UP Junior Marketing Association. It is the guiding force in the theory and practice of the core competency of the organization. It helps the members conceptualize marketing strategies, communicate with optimal quality, hone the skills of the applicants and members, and provide opportunities for them to improve through different avenues such as workshops"

var mppTitle=  "Marketing Point Persons";
var mppBody = "A. Privileges\nAccess to UP JMA’s marketing database\nAdvise on how to use the different documents of the JMaK\nGuidance on different approaches to marketing\nCandidacy for Member Marketer of the Semester\nB. Responsibilities\nSecurity of the JMaK and the database\nLink between TMS and team regarding marketing activities\nPreservation of UP JMA’s brand and image through professionalism";

var tipsTitle = "The Tips";
var tipsBody= ["1. Don’t be limited to a bond paper! You can even make your letter look like a brochure.","2. Programs to use: Word, Powerpoint, Photoshop etc!","3. Sponsor Privileges:","a. Top billing and top priority","b. Streamers on site","c. Logo on event poster","d. Logo on event ticket","e. Logo on all/selected promotional material (print and digital)","f. Logo on event teasers","g. Option to distribute fliers/premium items","h. Option to conduct a survey","i. Option to conduct a promotion game during/before the event","j. Option to set up a product booth","k. Option to air a company jingle","l. Option to partner with UP JMA Privilege Card","m. Acknowledgement during the event","n. Acknowledgement on media ads","o. Option to place logo on merchandise (shirts, mugs, etc.)","p. Option to provide products/services before and/or during event","q. Option to provide venue or equipment during the event","4. Have a donor package for an easy Php 5,000.00","5. Opening letter content:","* Greeting! (If you feel like it, you can think of more creative ways to say 'Hello!'","* What is UP JMA?","* What is your event?","* What is your event all about?","* When/where is your event?","* What do you want from the people you are addressing?","* Why would the people you are addressing want to support you?","* Why are you planning this even (beneficiaries, advocacies, etc.)?","* Who and how do the people contact in case they want to reach you?","* Thank you! (For your time, for your kindness, for etc.)","* Sincerely","6. Marketer’s Checklist","* A full understanding of and belief in your project’s concept","* A concept of the marketing letter approved by TMS","* A notepad to jot down important details (ex. Emails, times, names etc.)","* Good manner and right conduct","When calling SPONSORS:","* The Marketing letter file open or on hand","* A phone without a choppy connection","When doing face-to-face marketing:","* A full-color copy of the marketing letter for the manager/owner","* A PowerPoint presentation of your event (if possible)","* A Blank memorandum of agreement (MOA)","7. “We’re marketers, not beggars.” – Nigel Paras","Negotiating is on a case-to-case basis, especially when it comes to x-deals. Some ideas you should take into consideration","* 120% of x-deals according to the package amount","o Example: San Miguel accepts a Major Sponsor package but proposed to give P10, 000 worth of products, NEGOTIATE that San Miguel must give P12, 000 worth of products since they are sponsoring in kind and not in cash.","* Giving the package below the amount of x deals","* Half x deals, half cash or any other ration of x deals and cash","* Sponsors who are strict with documentation","8. When contacting sponsors, keep in mind:","* The JMA Image","* Your event/product’s purpose, market and status.","* The contact’s company’s purpose, market and status","* It’s a partnership"].join('\n') ;

var toolsTitle= "The Tools";
var toolsBody = "* Marketing Letter Template – see Google Drive\n* Banner\n* UP JMA Logos";

var fcTitle = "The TMS- MPP Flowchart";
var fcBody = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea provident, ad aspernatur molestias architecto eius, hic. Odio atque minus totam nulla similique? Nihil earum, amet quam autem quos dolorem explicabo!";

var rulesTitle = "The Rules";
var rulesBody = ["1. Always use the JMA LOGO. Please stick to it as much as possible.","2. You must have a BANNER or something that resembles a banner that will unify all the pages of your marketing letter. Either use the default one or create a custom banner for your event.","3. You may have a sidebar with your event specifics (date, venue, traffic, etc.) and contact details of the people in charge.","4. Packages and details must be in table form.","5. Opening letter must not go beyond ONE PAGE.","6. Font must be readable (e.g. Arial or Century Gothic Size 10) Italicize, bold, or underline all of the necessary details.","7. If you’re going to highlight, make sure the color matches to the rest of your letter.","8. Default type for editing: doc & ppt/hardcopy","9. Default type for sending: pdf/hardcopy"].join('\n');


